%% ASEN 3802 - Lab 3 - Main
% Task 1: Create NACA Airfoil Generator, Plot Results
% Task 2: Vortex Panel Method, N Panel Convergence
% Task 3: ...
% Task 4: ...
% Author: Cooper, Nathan, Sayer, Xander
% Date: Mar 31, 2026

clc; clear all; close all;

%% Task 1, NACA 0021, NACA 2421
% Airfoils for Task 1
airfoil1 = 'NACA_0021';
airfoil2 = 'NACA_2421';

N = 50; % Number of Panels for top and bottom each
c = 1; % Chord length

% Plotting and Calculations for Airfoil 1
[m,p,t] = extractAirfoilData(airfoil1); % Calc m,p,t
[x_b,y_b,y_c,x] = NACA_Airfoils(m,p,t,c,N); % Calc geometry
PlotAirfoil(x_b,y_b,y_c,x,c,airfoil1); % Plot geometry

% Plotting and Calculations for Airfoil 2
[m,p,t] = extractAirfoilData(airfoil2);
[x_b,y_b,y_c,x] = NACA_Airfoils(m,p,t,c,N);
PlotAirfoil(x_b,y_b,y_c,x,c,airfoil2);

% Functions for Part 1
function [x_b,y_b,y_c,x] = NACA_Airfoils(m,p,t,c,N)
    %{
    Inputs:
        m - max camber
        p - location of max camber
        t - max thickness
        c - chord length
        N - Number of Panels
    Outputs:
        x_b - X coordinates of boundary
        y_b - Y coordinates of boundary
        y_c - Mean camber line y coords
         x  - X coordinates generated by ray method
    %}
    % Create x value array using ray method
    x = GeometricXValues(N,c);
    % Calculates the thickness distribution of airfoil
    y_t = (t*c/0.2)*((0.2969*sqrt(x/c) - 0.1260*(x/c)-0.3516*(x/c).^2 + 0.2843*(x/c).^3 - 0.1036*(x/c).^4));
    % Preallocate arrays
    xi = zeros(1,length(x));
    dyc = zeros(1,length(x));
    y_c = zeros(1,length(x));

    % Finds the mean camber line. Splits it between before the maximum camber
    % position and after. Will go to 0 if there is no camber.
    for i = 1:length(x)
        % If before max camber position
        if x(i) < p*c
            % y coordinate camber modification
            y_c(i) = m*x(i)/p^2 * (2*p-x(i)/c);
            %dyc/dx
            dyc(i) = (2*p-2*x(i)/c)*m/p^2;
            % Angle calculation
            xi(i)= atan(dyc(i));
        % If after max camber position
        elseif x(i) >= p*c
            y_c(i) = m*(c-x(i))/(1-p)^2 * (1+(x(i)/c)-(2*p));
            dyc(i) = m/(1-p)^2*(2*p-2*x(i)/c);
            xi(i) = atan(dyc(i));
        end
    end
    
    x_L = x + y_t.*sin(xi);
    x_U = x - y_t.*sin(xi);
    y_L = y_c - y_t.*cos(xi);
    y_U = y_c + y_t.*cos(xi);
    % Concatenate Upper and Lower in CW Trailing Edge, modify indices so
    % doesn't double up array values, flip for correct order
    x_b = [x_L, fliplr(x_U(1:end-1))]; % Flip x_U so that goes from left to right
    y_b = [y_L, fliplr(y_U(1:end-1))]; % Flip y_U so matches flipped x_U
end

function [m,p,t] = extractAirfoilData(airfoilCode)
    %{
    Inputs: 
        airfoilCode - NACA_XXXX airfoil as a string, X's numbers
    Outputs:
        m - max camber
        p - location of max camber
        t - max thickness of airfoil
    %}
    code = airfoilCode(6:end); % Extract Numbers
    digits = code - '0'; % Convert to vector of digits
    m = digits(1)/100; % Calculate max camber
    p = digits(2)/10; % Calculate position of max camber 
    t = str2double(sprintf('%d%d',digits(3),digits(4)))/100; % Calculate thickness
end

function [x_array] = GeometricXValues(Number_of_Panels,C)

%GeometrixXValues finds X values based off the gemoetric method highlighted
%in class,
%This function takes the desired number of panels and the chord length. It
%takes N panels as equivalent to N rays, from the point c/2 to a circle
%with radius of c/2. Taking the number of rays over 2pi radians gives the
%equal angle between them. We make an array of rays, spaced by the equal
%angle we've found. Then we just take the dot product of the ray and the
%x-axis to get an array of x values, between 0 and c.
%
% Author: Sayer Gage
% Collaborators: Xander Lotito
% Date: 03/31/26
% Modified change from 2pi to pi to get rid of doubling coord error
Number_of_Rays = Number_of_Panels; %The number of rays we have should be
%equivalent to the number of panels we want.
Angle = pi / Number_of_Rays; %The equal angle should just be the number of arrays 
%divided by the full arc of the circle
Angle_array = 0:Angle:pi; %this is an array describing all the rays, as described
%by their angle clockwise from the TE
x_array = (C/2)*cos(Angle_array) + C/2; %This takes the x-projection of each
%ray to get an array of N+1 x points on the x-axis, giving N panels.
end

function PlotAirfoil(x_b,y_b,y_c,x,c,name)
    %{
    Inputs:
        x_b - x coords TE on bottom to LE to on TE top
        y_b - y coords, same CW order from TE
        y_c - mean camber line
         x  - x coordinates for camber line plotting
        c - chord length for plot scaling
        name - airfoil name for title
    Outputs:
        Plot of Airfoil geometry
    %}
    figure(); hold on; grid on;
    plot(x_b,y_b,"Marker",".",DisplayName="Airfoil Boundary"); % Plotting Boundary of Airfoil
    % Adding Limits to x and y
    xlim([-0.05*c 1.05*c]);
    ylim([-c c]);
    % Labels and Title
    xlabel("X Position (0 to c)");
    ylabel("Y Position");
    title("Geometry of " + name + " Airfoil",Interpreter="none");
    % Only plot camber line if airfoil is cambered, Add legend for camber line vs boundary
    if any(y_c) % Runs if any values of y_c not equal to 0
        plot(x,y_c,'-b',DisplayName="Mean Camber Line"); % Plot camber line with x coordinates from ray generation
    end
    legend("show");
end

%% Task 2, Vortex Panel Method
% Find cl of NACA 0012 at Alpha = 12 deg, Find N panels to converge to < 1% error
p2plot = 1;
if p2plot == 1
% Input parameters for Vortex Panel
airfoil3 = 'NACA_0012';
c = 1;
NumPanels = linspace(10,500,491);
alpha = 12; % AoA, degrees
[m,p,t] = extractAirfoilData(airfoil3);

predicted_cl = zeros(1,length(NumPanels));
% Loop for N panel convergence
for i = 1:length(NumPanels)
    [x_b,y_b,y_c,x] = NACA_Airfoils(m,p,t,c,NumPanels(i));
    predicted_cl(i) = Vortex_Panel(x_b,y_b,alpha);
end

% Caluclate "exact" cl with large number of panels, store to save future run time
% [x_b,y_b,y_c,x] = NACA_Airfoils(m,p,t,c,3000);
% exact_cl = Vortex_Panel(x_b,y_b,alpha);
exact_cl = 1.438326093800802;

% Percent Difference Formula, check if % diff < 1% error
[val, idx] = find((abs(exact_cl-predicted_cl)./((exact_cl + predicted_cl)./2) .* 100) < 1,1,"first");

% Plot of predicted cl vs number of panels used for calculation
figure(); hold on;
plot(2*NumPanels,predicted_cl,'b');
yline(exact_cl,'k');
yline(1.01*exact_cl,'r--');
yline(0.99*exact_cl,'r--');
xline(2*NumPanels(idx),'g--',LineWidth=2);
xlabel("Total Number of Panels (N)");
ylabel("Predicted Sectional Lift Coefficient (c_l)");
title("Predicted Sectional Lift Coefficient vs Number of Panels");
legend("Predicted c_l","Exact c_l","1% Error Bounds","","Min Number of Panels for < 1% Error",Location="southeast");

% Print needed info to command window
fprintf("Sectional Lift Coefficient (cl) for NACA 0012 at 12 degrees: %.3f \n", exact_cl);
fprintf("Min Number of Panels Needed for < 1 Percent Error from Exact: %.1f \n",2*NumPanels(idx));

% Extracting Data For Table
% Use 10, 50, 100, 200, 500 (Multiply by 2 for Total Panels)
% Cl, Num Panels, Relative Error, Min Panels for Convergence (separate)
Panels = [10, 50, 100, 200, 500];
TotPanels = zeros(1,5);
Cls = zeros(1,5);
RelativeError = zeros(1,5);
Names = ["Tot Panels","Cl","Relative Error"];
for i = 1:5
    idx = find(NumPanels == Panels(i),1,"first");
    Cls(i) = predicted_cl(idx);
    TotPanels(i) = Panels(i);
    RelativeError(i) = (abs(exact_cl-Cls(i))/(exact_cl+Cls(i))/2) * 100; % Convert to %
end
T = table(2.*Panels',Cls',RelativeError','VariableNames',Names);
end

% Functions for Part 2
function [CL] = Vortex_Panel(XB,YB,ALPHA)
% Modified, removed VINF from inputs b/c not used in function
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% Input:                           %
%                                  %
% XB  = Boundary Points x-location %
% YB  = Boundary Points y-location %
% VINF  = Free-stream Flow Speed   %
% ALPHA = AOA                      %
%                                  %
% Output:                          %
%                                  %
% CL = Sectional Lift Coefficient  %
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

%%%%%%%%%%%%%%%%%%%%%%
% Convert to Radians %
%%%%%%%%%%%%%%%%%%%%%%

ALPHA = ALPHA*pi/180;

%%%%%%%%%%%%%%%%%%%%%
% Compute the Chord %
%%%%%%%%%%%%%%%%%%%%%

CHORD = max(XB)-min(XB);

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% Determine the Number of Panels %
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

M = max(size(XB,1),size(XB,2))-1;
MP1 = M+1;

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% Intra-Panel Relationships:                                  %
%                                                             %
% Determine the Control Points, Panel Sizes, and Panel Angles %
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

for I = 1:M
    IP1 = I+1;
    X(I) = 0.5*(XB(I)+XB(IP1));
    Y(I) = 0.5*(YB(I)+YB(IP1));
    S(I) = sqrt( (XB(IP1)-XB(I))^2 +( YB(IP1)-YB(I))^2 );
    THETA(I) = atan2( YB(IP1)-YB(I), XB(IP1)-XB(I) );
    SINE(I) = sin( THETA(I) );
    COSINE(I) = cos( THETA(I) );
    RHS(I) = sin( THETA(I)-ALPHA );
end

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% Inter-Panel Relationships:             %
%                                        %
% Determine the Integrals between Panels %
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

for I = 1:M
    for J = 1:M
        if I == J
            CN1(I,J) = -1.0;
            CN2(I,J) = 1.0;
            CT1(I,J) = 0.5*pi;
            CT2(I,J) = 0.5*pi;
        else
            A = -(X(I)-XB(J))*COSINE(J) - (Y(I)-YB(J))*SINE(J);
            B = (X(I)-XB(J))^2 + (Y(I)-YB(J))^2;
            C = sin( THETA(I)-THETA(J) );
            D = cos( THETA(I)-THETA(J) );
            E = (X(I)-XB(J))*SINE(J) - (Y(I)-YB(J))*COSINE(J);
            F = log( 1.0 + S(J)*(S(J)+2*A)/B );
            G = atan2( E*S(J), B+A*S(J) );
            P = (X(I)-XB(J)) * sin( THETA(I) - 2*THETA(J) ) ...
              + (Y(I)-YB(J)) * cos( THETA(I) - 2*THETA(J) );
            Q = (X(I)-XB(J)) * cos( THETA(I) - 2*THETA(J) ) ...
              - (Y(I)-YB(J)) * sin( THETA(I) - 2*THETA(J) );
            CN2(I,J) = D + 0.5*Q*F/S(J) - (A*C+D*E)*G/S(J);
            CN1(I,J) = 0.5*D*F + C*G - CN2(I,J);
            CT2(I,J) = C + 0.5*P*F/S(J) + (A*D-C*E)*G/S(J);
            CT1(I,J) = 0.5*C*F - D*G - CT2(I,J);
        end
    end
end

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% Inter-Panel Relationships:           %
%                                      %
% Determine the Influence Coefficients %
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

for I = 1:M
    AN(I,1) = CN1(I,1);
    AN(I,MP1) = CN2(I,M);
    AT(I,1) = CT1(I,1);
    AT(I,MP1) = CT2(I,M);
    for J = 2:M
        AN(I,J) = CN1(I,J) + CN2(I,J-1);
        AT(I,J) = CT1(I,J) + CT2(I,J-1);
    end
end
AN(MP1,1) = 1.0;
AN(MP1,MP1) = 1.0;
for J = 2:M
    AN(MP1,J) = 0.0;
end
RHS(MP1) = 0.0;

%%%%%%%%%%%%%%%%%%%%%%%%
% Solve for the gammas %
%%%%%%%%%%%%%%%%%%%%%%%%

GAMA = AN\RHS';

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% Solve for Tangential Veloity and Coefficient of Pressure %
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

for I = 1:M
    V(I) = cos( THETA(I)-ALPHA );
    for J = 1:MP1
        V(I) = V(I) + AT(I,J)*GAMA(J);
    end
    CP(I) = 1.0 - V(I)^2;
end

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% Solve for Sectional Coefficient of Lift %
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

CIRCULATION = sum(S.*V);
CL = 2*CIRCULATION/CHORD;
end